name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/work-wise-stt ./speech-to-text-service
          docker push ${{ secrets.DOCKER_USERNAME }}/work-wise-stt
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-image
  #   steps:
  #     - name: Trigger Deployment
  #       run: |
  #         curl --fail -X POST http://<your-server-ip>:<port>/deploy -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}"
